homeassistant:
  name: Home
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  elevation: !secret ha_elevation
  temperature_unit: C
  unit_system: metric
  time_zone: America/Montreal
  customize: !include_dir_merge_named customizations

http:

config:

group: !include_dir_named groups

alert: !include_dir_named alerts

automation: !include_dir_list automations

proximity: !include_dir_named proximities

script: !include_dir_named scripts

google: !include google_oauth.yaml

media_player: !include_dir_list media_players

notify: !include_dir_list notifiers

#input_boolean: !include_dir_named input_booleans

binary_sensor: !include_dir_list binary_sensors

device_tracker: !include_dir_list device_trackers

sensor: !include_dir_list sensors

cover: !include_dir_list covers

zone: !include_dir_list zones

logbook:
  exclude:
    domains:
      - sun
sun:

history:

frontend:

discovery:

conversation:
